### ISSUE TITLE
Feature Request for Themer Plugin - Quick Theme Edit

### ISSUE THREAD

**Issue by hairyfred** [Vendicated/AliucordPlugins#12]
Add a built in editor to edit your current themes JSON File
Similar to how Desktop Discord Clients have a quick css editor

Doesn't need a fancy gui, just a page with the raw text from the json file and a save button

**Comment by Vendicated** [comment]
Soon

![img](https://cdn.discordapp.com/attachments/811261478875299840/882320059752669214/Screenshot_20210831-194441.jpg)

![img](https://cdn.discordapp.com/attachments/811261478875299840/882318975613165628/Screenshot_20210831-194021.jpg)

**Comment by Vendicated** [comment]
https://github.com/Vendicated/AliucordPlugins/commit/73f4b5598f43d1c1a4b91a350560925c5aba942d
