### ISSUE TITLE
Themer- Toast notification

### ISSUE THREAD

**Issue by ItsLogic** [Vendicated/AliucordPlugins#13]
### Feature request
Option to disable the toast notification on app startup
 ### Benefit
No more toast notification getting in the way every time the app is launched
### Why
The toast notification currently doesnt add anything to the plugin other than telling the user if a theme was applied and which one it was(which can just as easily be discovered by the user if they look at the discord client and see if the theme has changed)

I feel as though this would help users with small screens as toast notifications can take up a significant portion of the screen and it sort of annoys me seeing a toast notification every time I launch the app which tells me information I already know

**Comment by Vendicated** [comment]
gone https://github.com/Vendicated/AliucordPlugins/commit/c45fd600fdfc797db48c5b1db78e59f620a6c06f
