### ISSUE TITLE
[Themer] File picker API too new for Android 7

### ISSUE THREAD

**Issue by Cynosphere** [Vendicated/AliucordPlugins#14]
NewPipe was able to give me a file picker window but it never sent any file data back to Discord.
![](https://i.imgur.com/l5FlLGz.jpeg)

**Comment by Vendicated** [comment]
for now just manually move the file to Aliucord/themes and restart / use the load missing themes button

Importing themes will be improved in the future, this is just a temporary solution

**Comment by Cynosphere** [comment]
Is there a workaround for font though?

**Comment by Vendicated** [comment]
uh i just reworked the way fonts work and moved it into theme files now (https://github.com/Vendicated/AliucordPlugins/commit/d86db6474d96c4deee45dc7f1310bd344b80f3b1), via the `fonts` key for all fonts or `font_some_font_name` for a specific font
