### ISSUE TITLE
Themer- Inconsistent Font Application

### ISSUE THREAD

**Issue by ItsLogic** [Vendicated/AliucordPlugins#17]
# Issue
When restarting the app some fonts get reset.
# Screenshots
Just after applying the theme:
![Screenshot_20210815-203131__01](https://user-images.githubusercontent.com/38233332/129490356-8d9a7f93-e1c0-4018-af0d-41d846e66201.jpg)
![Screenshot_20210815-203215__01](https://user-images.githubusercontent.com/38233332/129490373-653a4edd-1b56-4bbc-b300-0bfe27d0c20e.jpg)
![Screenshot_20210815-203136__01](https://user-images.githubusercontent.com/38233332/129490376-b466ba45-b09f-4dda-bd25-498ec24b62ae.jpg)

After restarting the app:
![Screenshot_20210815-203109__01__01](https://user-images.githubusercontent.com/38233332/129490413-cbe7a2aa-c843-4b6a-9849-44d59e179e1c.jpg)
![Screenshot_20210815-203057__01](https://user-images.githubusercontent.com/38233332/129490412-30134f08-3087-45ee-9080-dd30e273829c.jpg)
![Screenshot_20210815-203102__01](https://user-images.githubusercontent.com/38233332/129490410-b8ec439d-6dc6-47a3-bff7-99891ccd0c8e.jpg)

# Impacted fonts
The ones I have noticed were the bold header fonts. The one for server name, channel name(header) and the user settings header

**Comment by Vendicated** [comment]
Should be fixed in 3.1.0! Please confirm it works correctly now

**Comment by ItsLogic** [comment]
The issue is now fixed, thanks.
