### ISSUE TITLE
Themer bug

### ISSUE THREAD

**Issue by fym35** [Vendicated/AliucordPlugins#18]
When more themes are in the message it always downloads the first one
![IMG_20210816_070132](https://user-images.githubusercontent.com/57803365/129513544-d8b8bad5-6917-4232-b26f-74e854f2277a.jpg)
![Screenshot_2021-08-16-07-01-12-826_com aliucord](https://user-images.githubusercontent.com/57803365/129513547-1ee744ff-c84e-4daa-a6ab-cfeb33cd00e2.jpg)

**Comment by Vendicated** [comment]
fixed in https://github.com/Vendicated/AliucordPlugins/commit/1b03423251c79b9bc5c344ae356390ae6c43521f
