### ISSUE TITLE
[ EmojiUtility ] option not to close reaction menu after reacting

### ISSUE THREAD

**Issue by yesyesyes69** [Vendicated/AliucordPlugins#19]
with rate limit of 1 reaction per second or 1.5s because tos

so i can put 20 kekw's on 1 message with less effort and less remembering which ive already reacted with as they are similar
i suppose this could be related to this plugin

**Comment by Vendicated** [comment]
already a feature, long press the react button

**Comment by Vendicated** [comment]
why the reaction? Did I understand your request incorrectly?
