### ISSUE TITLE
[DedicatedPluginSettings] Ability to hide specific plugins

### ISSUE THREAD

**Issue by pointydev** [Vendicated/AliucordPlugins#22]
There are certain plugins that I'm pretty satisfied with my configuration of, and it'd be nice to be able to hide those and take the few taps more to get to them if I ever need to, cleaning up the main settings scroller.

~pointy

**Comment by Vendicated** [comment]
soon:tm:

**Comment by Vendicated** [comment]
Added in https://github.com/Vendicated/AliucordPlugins/commit/6b7503052d6f8026e17457b24673ebe44dd3820b
