### ISSUE TITLE
[Emoji Utility] Add button to copy emoji code to EmojiUtility menu

### ISSUE THREAD

**Issue by Delphox** [Vendicated/AliucordPlugins#23]
Code such as <:aliucord:860599530956783656>

It's useful both for servers with NQN bot to post emojis/add reactions with the /react option, and also for getting the raw emoji code for adding emojis to the subject line in a channel subject.

**Comment by Vendicated** [comment]
Added in https://github.com/Vendicated/AliucordPlugins/commit/9989930815edc1728a8f5fe51a17501194975dbd
