### ISSUE TITLE
[TapTap] reply on invalid channel

### ISSUE THREAD

**Issue by WeMayNeverKnow** [Vendicated/AliucordPlugins#25]
When I double tap on an invalid channel it makes the things appear which it shouldn't do

**Comment by WeMayNeverKnow** [comment]
Also the cursor isn't placed on the message box when you double tap on a message

**Comment by Vendicated** [comment]
just don't taptap on an invalid channel. I don't think this matters since it's not a serious issue and just a visual issue so I probably won't fix it

**Comment by onlyluckyloser** [comment]
Ah okey, Thanks for the information, i just thought this plugin would be
usefull for me, i want it so idk if i can get it from some people and send
me the link on email or discord
dc: ThreeToedNpc476#2064
Email: ***@***.***

Am Fr., 5. Nov. 2021 um 18:01 Uhr schrieb Ven ***@***.***>:
