### ISSUE TITLE
[EmojiUtility] Option to clone/copy emojis from user custom status

### ISSUE THREAD

**Issue by ow0x** [Vendicated/AliucordPlugins#26]
Hi, 

opening this issue/feature request as per your request in #plugins-support. 

It would be really handy dandy useful if there is a way to clone emojis from user's custom status with your EmojiUtility plugin, similar to how it shows the nice tooltip at bottom when we click on an emoji in a message.

Ty.

**Comment by Vendicated** [comment]
added in https://github.com/Vendicated/AliucordPlugins/commit/9989930815edc1728a8f5fe51a17501194975dbd
