### ISSUE TITLE
[Themer] Add settings into appearance

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [Vendicated/AliucordPlugins#27]
Heya, just wondering why Themer doesn't add all of the settings into Appearance since it seems like it'd fit there and it'd be more accessible then having to go to the settings in plugins or using the Dedicated Plugins Settings

**Comment by Vendicated** [comment]
I don't understand how that would be more accessible  since it'd still be the same amount of clicks. use dedicated plugin settings, you can even hide all plugins but themer from it
