### ISSUE TITLE
[EmojiUtility] Make non-accessible emojis greyed like before in reactions.

### ISSUE THREAD

**Issue by WitherredAway** [Vendicated/AliucordPlugins#28]
Would it be possible to disable this for reactions? Since it doesn't help anyway, it's just hard to find the emojis i can actually use since it un-greys out all non-accessible emojis.

**Comment by Vendicated** [comment]
that's nitrospoof ungreying them. doesn't emoji utilities option to hide unusable emojis hide them from reactions menu? make sure the plugin is updated

**Comment by WitherredAway** [comment]
Oh shit my bad, yeah that's nitrospoof idk why i came here. And no, emojiutility's hide unusable emojis doesn't grey them, it's updated. I'll close this issue and open one on nitrospoof 🤣 Thanks for the response!
