### ISSUE TITLE
[WIP - Emoji Replacer] Files

### ISSUE THREAD

**Issue by gaussandhisgun** [Vendicated/AliucordPlugins#39]
So you mentioned you already did manage to make noto color emojis work on that. Can you share the file please? Also a suggestion, while i am here. I would like to see support for github.com/C1710/blobmoji if possible. Thanks in advance.

p.s. it would be fun if i reminded you that you have that pligin WIP at all with this, and yes i do understand there are a probability that you have no free time.

**Comment by gaussandhisgun** [comment]
nevermind, found it - https://github.com/Vendicated/AliucordPlugins/blob/builds/EmojiReplacer.zip?raw=true

yes i do know that it's unstable and can possibly cause data loss

**Comment by Vendicated** [comment]
not data loss but like it might fuck your discord up lol don't blame me if that happens

**Comment by gaussandhisgun** [comment]
it did not do anything anyway. either i am too stupid to make it work or its all because there are no documentation yet

**Comment by Vendicated** [comment]
because ae u need to download https://github.com/Vendicated/AliucordPlugins/blob/main/EmojiReplacer/noto.zip to your download folder

**Comment by gaussandhisgun** [comment]
what is the exact path to put it, i have it currently in `/sdcard/Aliucord/emoji` for some reason :D
