### ISSUE TITLE
[TapTap] Error from installing the plugin with PluginDownloader


### ISSUE THREAD

**Issue by WhenFreedom** [Vendicated/AliucordPlugins#51]
This isn't only me it's happening to, when I try installing the plugin with PluginDownloader, a toast appears saying:
 "Failed to load plugin: TapTap" 

And the plugin doesn't appear at all in the Plugins List. 

I backed up the previous version before testing out whether the plugin downloads, and the version I backed up works perfectly. It's only now this has began happening.

**Comment by Vendicated** [comment]
Just restart and it works

**Comment by WhenFreedom** [comment]
Oh yeah, now I see it working. 💀

I just installed the plugin again, restarted, it didn't work after first restart. 

Then I went to the plugins folder in file explorer, refreshed the folder, restarted Aliucord the second time and it's working again. 

But yeah, apologies.
