### ISSUE TITLE
[EmojiUtility] Clear recent emoji

### ISSUE THREAD

**Issue by nattadasu** [Vendicated/AliucordPlugins#52]
As the title suggest, make a button to allow user clear their recent emoji on emoji picker.

Why? Why not?

**Comment by Vendicated** [comment]
just clear app data xd

**Comment by nattadasu** [comment]
Well yes, but it also clear configurations set on setting :'D

Plus, Desktop users can clear it with JS snippet provided, ofc there's interest for this feature :eyes:
