### ISSUE TITLE
YouTube Embeds

### ISSUE THREAD

**Issue by knightmob** [Vendicated/AliucordPlugins#57]
Hi there dev, YouTube embed is not playing it will display this message, hope you'll fix this dev and btw interesting plug in😁 message![Screenshot_2022_0214_103329.png](https://user-images.githubusercontent.com/76065610/153790409-c6750599-bb54-4cf1-95d8-5b11f3c04a3b.png)

**Comment by Vendicated** [comment]
It's just Youtubes own embed, if it shows that that's a youtube issue or the uploader doesn't allow embedding. I can't fix that
