### ISSUE TITLE
Feature Request for Tap Tap

### ISSUE THREAD

**Issue by alcatrazblaze** [Vendicated/AliucordPlugins#6]
It would be nice if double tapping a message would also open the keyboard

Right now, the focus comes to the text box but an additional touch on the text box is required to get the keyboard up

**Comment by Vendicated** [comment]
Implemented in https://github.com/Vendicated/AliucordPlugins/commit/f61eaf3e904fb84926b38e7ea63c2e97a02098cf. It is off by default, so enable it in the settings
