### ISSUE TITLE
[PlayableEmbeds] Always show error

### ISSUE THREAD

**Issue by Bluscream** [Vendicated/AliucordPlugins#71]
![Screenshot_2022-09-01-11-45-45-663](https://user-images.githubusercontent.com/3318223/187884902-98135453-d5c3-476c-9276-f775a6bca16f.jpeg)

**Comment by Vendicated** [comment]
This is an issue with your webview or connection, I can't fix that

**Comment by Bluscream** [comment]
How can i even debug that then?
