### ISSUE TITLE
[TextFilePreview] Add show/hide default state settable

### ISSUE THREAD

**Issue by Palloxin** [Vendicated/AliucordPlugins#76]
I mean the eye icon on text files. That is show/hide.
So i would like to keep by default the preview of text file hidden.

**Comment by Happ1ness-dev** [comment]
> So i would like to keep by default the preview of text file hidden.

Same. I'm a bit concerned about the fact that it reloads the file preview whenever I scroll away even a little.

Kind of worried about the API spamming, because there seems to be no caching implemented.
