### ISSUE TITLE
[EmojiUtility] EmojiStickerUtility

### ISSUE THREAD

**Issue by MatadorProBr** [Vendicated/AliucordPlugins#9]
It would be cool if the EmojiUtility plugin came with stickers support too and if that happens I think will need also have to change the plugin name, like EmojiStickerUtility?

(For more information: https://github.com/Aliucord/plugin-requests/issues/133)

**Comment by Vendicated** [comment]
probably won't do that because stickers are apng/lottie so very awkward format to work with and I cant even use them due to not having expensive nitro so i dont have much interest in it

**Comment by Vendicated** [comment]
Yeah I don't think I will be doing that, sorry!
